### ISSUE TITLE
example for concourse pipelines

### ISSUE THREAD

**Issue by dodizzle** [getoutreach/jsonnet-libs#28]
This looks really useful but I'm not sure how to supply the params to create the pipeline.
I'm stuck at:
{
   "groups": [ ],
   "jobs": [ ],
   "resource_types": [ ],
   "resources": [ ]
}
Can you create a simple working example?

**Comment by josdotso** [comment]
+1. The link in the readme is broken: https://github.com/getoutreach/concourse-example/blob/master/ci/pipeline.jsonnet
